# One of the main reasons for choosing YAML over JSON is being able to use comments

# First Feed
-
  url: http://date.jsontest.com/
  parser: parser_example
  destination: file://date
  # I don't use s3 examples in the sample, but this is how you would do them
  # The first (domain-like) path component is the Bucket and the rest is the Key
  #destination: s3://my_bucket/date.json

# Second Feed
-
  category: Top News
  subcategory: Top News
  url: http://www.filltext.com/?rows=10&fname={firstName}&lname={lastName}&tel={phone|format}&address={streetAddress}&city={city}&state={usState|abbr}&zip={zip}
  parser: addresses_filltext
  destination: file://addresses/1

# Third Feed
-
  category: News
  subcategory: Local
  url: http://beta.json-generator.com/api/json/get/FrBbyBY
  parser: addresses_json_generator
  destination: file://addresses/2
